export const title = {
    homepageTitle: 'A place to practice your automation skills!',
    apparelTitle: 'Apparel & accessories',
    makeupTitle: 'Makeup',
    skincareTitle: 'Skincare',
    fragranceTitle: 'Fragrance',
    menTitle: 'Men',
    haircareTitle: 'Hair Care',
    booksTitle: 'Books',
    shoesTitle: 'Shoes',
    tshirtsTitle: 'T-shirts',
    makeupCheeksTitle: 'Cheeks',
    makeupEyesTitle: 'Eyes',
    makeupFaceTitle: 'Face',
    makeupLipsTitle: 'Lips',
    makeupNailsTitle: 'Nails',
    makeupSetsTitle: 'Value Sets',
    skincareEyesTitle: 'Eyes',
    skincareFaceTitle: 'Face',
    skincareGiftsTitle: 'Gift Ideas & Sets',
    skincareHandsNailsTitle: 'Hands & Nails',
    skincareSunTitle: 'Sun',
    fragranceMenTitle: 'Men',
    fragranceWomenTitle: 'Women',
    menBodyShowerTitle: 'Body & Shower',
    menFragranceTitle: 'Fragrance Sets',
    menShaveTitle: 'Pre-Shave & Shaving',
    menSkincareTitle: 'Skincare',
    hairConditionerTitle: 'Conditioner',
    hairShampooTitle: 'Shampoo',
    booksAudioCDTitle: 'Audio CD',
    booksPaperbackTitle: 'Paperback',
    benefitTitle: 'Benefit',
    panteneTitle: 'Pantene',
    macTitle: 'M·A·C',
    lancomeTitle: 'Lancôme',
    gucciTitle: 'Gucci',
    armaniTitle: 'Giorgio Armani',
    doveTitle: 'Dove',
    calvinTitle: 'Calvin Klein',
    bulgariTitle: 'Bvlgari',
    sephoraTitle: 'Sephora',
    aboutUsTitle: 'About Us',
    privacyPolicyTitle: 'Privacy Policy',
    returnPolicyTitle: 'Return Policy',
    shippingTitle: 'Shipping',
    contactUsTitle: 'Contact Us',
    siteMapTitle: 'Site Map',
    loginTitle: 'Account Login',
    createAccount: 'Create Account',
    specialPage: 'Special Offers',
    myAccount: 'My Account',
    myWishList: 'My wish list',
    myAccountInformation: 'My Account Information',
    changePassword: 'Change Password',
    manageAddressBook: 'Address Book',
    orderHistory: 'My Order History',
    transactionHistory: 'My Transactions',
    downloads: 'Account Downloads',
    notifications: 'Notifications and Newsletter',
    cartTitle: 'Shopping Cart',
    checkoutTitle: 'Checkout Confirmation',
    shippingAddressTitle: 'Delivery Information',
    paymentTitle: 'Payment Information',
    newAddressTitle: 'Checkout Address',
    firstFeaturedItemTitle: 'Skinsheen Bronzer Stick'
}