export const title = {
    homepageTitle: 'A place to practice your automation skills!',
    loginTitle: 'Account Login',
    createAccount: 'Create Account',
    myAccount: 'My Account',
    myWishList: 'My wish list',
    myAccountInformation: 'My Account Information',
    changePassword: 'Change Password',
    manageAddressBook: 'Address Book',
    orderHistory: 'My Order History',
    transactionHistory: 'My Transactions',
    downloads: 'Account Downloads',
    notifications: 'Notifications and Newsletter',
    cartTitle: 'Shopping Cart',
    checkoutTitle: 'Checkout Confirmation',
    shippingTitle: 'Delivery Information',
    paymentTitle: 'Payment Information',
    newAddressTitle: 'Checkout Address',
}