export const urls = {
    loginPage: '/index.php?rt=account/login',
    createNewAccount: '/index.php?rt=account/create',
    registerSuccess: '/index.php?rt=account/success',
    accountPage: '/index.php?rt=account/account',
    wishlistPage: '/index.php?rt=account/wishlist',
    editAccountDetails: '/index.php?rt=account/edit',
    changePassword: '/index.php?rt=account/password',
    manageAddressBook: '/index.php?rt=account/address',
    orderHistory: '/index.php?rt=account/history',
    transactionHistory: '/index.php?rt=account/transactions',
    downloads: '/index.php?rt=account/download',
    notifications: '/index.php?rt=account/notification',
    loggingOut: '/index.php?rt=account/logout',
    specialsPage: '/index.php?rt=product/special',
    euroPage: '/index.php?rt=index/home&currency=EUR',
    sterlingPage: '/index.php?rt=index/home&currency=GBP',
    dollarPage: '/index.php?rt=index/home&currency=USD',
    firstFeaturedItem: '/index.php?rt=product/product&product_id=50',
    cartPage: '/index.php?rt=checkout/cart',
    checkoutPage: '/index.php?rt=checkout/confirm',
    editShippingPage: '/index.php?rt=checkout/shipping&mode=edit',
    newShippingAddress: 'index.php?rt=checkout/address/shipping',
    editPaymentPage: '/index.php?rt=checkout/payment&mode=edit',
    newPaymentAddress: '/index.php?rt=checkout/address/payment',
    returnPolicyPage: '/index.php?rt=content/content&content_id=3',
    placeOrderSuccess: '/index.php?rt=checkout/success',
};