export const urls = {
    loginPage: '/index.php?rt=account/login',
    createNewAccount: '/index.php?rt=account/create',
    registerSuccess: '/index.php?rt=account/success',
    specialsPage: '/index.php?rt=product/special',
    euroPage: '/index.php?rt=index/home&currency=EUR',
    sterlingPage: '/index.php?rt=index/home&currency=GBP',
    dollarPage: '/index.php?rt=index/home&currency=USD',
    firstFeaturedItem: '/index.php?rt=product/product&product_id=50',
    cartPage: '/index.php?rt=checkout/cart',
    checkoutPage: '/index.php?rt=checkout/confirm',
    editShippingPage: '/index.php?rt=checkout/shipping&mode=edit',
    newShippingAddress: 'index.php?rt=checkout/address/shipping',
    editPaymentPage: '/index.php?rt=checkout/payment&mode=edit',
    newPaymentAddress: '/index.php?rt=checkout/address/payment',
    placeOrderSuccess: '/index.php?rt=checkout/success',
};